### PR TITLE
Replace failure with thiserror

### PR DESCRIPTION
**Pull request by upsuper**
[`failure`](https://github.com/rust-lang-nursery/failure) has been deprecated in favor of `thiserror`. This PR replaces it.

### CODE REVIEW

**Comment by victorporof** [comment]
I wonder if this conflicts with usage in m-c at all.

**Comment by upsuper** [comment]
I'm going to update m-c as well.

**Comment by victorporof** [comment]
@upsuper Do you have a link to a bug in m-c?

**Comment by upsuper** [comment]
Nope. I'll create one when I have the patch :)

I don't think this would affect downstream crates, as `Fail` is implemented for all `Error` types. The only meaningful difference is that backtrace support is dropped, which m-c doesn't use anyway.

**Comment by upsuper** [comment]
Meta bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1681898

**Comment by upsuper** [comment]
Oh actually there is a security advisory about the deprecation of failure: https://rustsec.org/advisories/RUSTSEC-2020-0036.html

**Comment by upsuper** [comment]
Based on experience on agashlin/comedy-rs#13, this would require a minor version bump, because `failure` without `std` feature doesn't really have `impl Fail` for error.

**Comment by upsuper** [comment]
Hey @victorporof, what do you think about this?

After [removing `failure` from `bits_client`](https://bugzilla.mozilla.org/show_bug.cgi?id=1684238), dependents of rkv and crates of lucet sandbox compilers are the last crates which are still using `failure`. I've contacted maintainer of lucet sandbox compilers, and from January next year, they are going to work on catching up with their upstream which has dropped `failure` dependencies for long. By then dependents of rkv would be the only reason we can't remove dependency of `failure` in m-c.

If you can merge this and release a new version, I can raise patch to update m-c to vendor the new version and fix up things.

**Comment by upsuper** [comment]
Ping for this.

**Comment by ncloudioj** [comment]
@upsuper My apologies for the late response.

Looking into your patch now.

**Review by ncloudioj — APPROVED** [review]
LGTM! @upsuper Thanks for the patch! 

@victorporof Could you bump the version (minor) and publish it so that @upsuper can proceed with the rest of the work in m-c?

**Comment by upsuper** [comment]
Thanks! I'll look into this over this weekend.

**Comment by victorporof** [comment]
Done.

**Pull request merged**
